kind: Template
apiVersion: v1
metadata:
  name: f8cluster
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: f8cluster
  type: Opaque
  data:
    db.host: ZGI=
    db.port: NTQzMg==
    db.user: cG9zdGdyZXM=
    db.password: bXlzZWNyZXRwYXNzd29yZA==
    sentry.dsn: c2VjcmV0
- apiVersion: v1
  kind: Secret
  metadata:
    name: f8cluster-config-files
  type: Opaque
  data:
    oso.clusters: >-
      DQp7DQogICAgImNsdXN0ZXJzIjogWw0KICAgICAgICB7DQogICAgICAgICAgICAibmFtZSI6InVzLWVhc3QtMiIsDQogICAgICAgICAgICAiYXBpLXVybCI6Imh0dHBzOi8vYXBpLnN0YXJ0ZXItdXMtZWFzdC0yLm9wZW5zaGlmdC5jb20iLA0KICAgICAgICAgICAgImFwcC1kbnMiOiI4YTA5LnN0YXJ0ZXItdXMtZWFzdC0yLm9wZW5zaGlmdGFwcHMuY29tIiwNCiAgICAgICAgICAgICJzZXJ2aWNlLWFjY291bnQtdG9rZW4iOiJmWDBuSDNkNjhMUTZTSzV3QkU2UWVLSjZYOEFaR1ZRTzNkR1FaWkVUYWtobWdtV0FxcjJLREZYRTY1S1V3Qk82OWFXb3EiLA0KICAgICAgICAgICAgInNlcnZpY2UtYWNjb3VudC11c2VybmFtZSI6ImRzYWFzIiwNCiAgICAgICAgICAgICJ0b2tlbi1wcm92aWRlci1pZCI6ImY4NjdhYzEwLTVlMDUtNDM1OS1hMGM2LWI4NTVlY2U1OTA5MCIsDQogICAgICAgICAgICAiYXV0aC1jbGllbnQtaWQiOiJhdXRoZWFzdDIiLA0KICAgICAgICAgICAgImF1dGgtY2xpZW50LXNlY3JldCI6ImF1dGhlYXN0MnNlY3JldCIsDQogICAgICAgICAgICAiYXV0aC1jbGllbnQtZGVmYXVsdC1zY29wZSI6InVzZXI6ZnVsbCINCiAgICAgICAgfSwNCiAgICAgICAgew0KICAgICAgICAgICAgIm5hbWUiOiJ1cy1lYXN0LTJhIiwNCiAgICAgICAgICAgICJhcGktdXJsIjoiaHR0cHM6Ly9hcGkuc3RhcnRlci11cy1lYXN0LTJhLm9wZW5zaGlmdC5jb20iLA0KICAgICAgICAgICAgImFwcC1kbnMiOiIxMjM0LnN0YXJ0ZXItdXMtZWFzdC0yYS5vcGVuc2hpZnRhcHBzLmNvbSIsDQogICAgICAgICAgICAic2VydmljZS1hY2NvdW50LXRva2VuIjoiYWs2MVQ2UlNBYWNXRnJ1aDF2WlA4Y3lVT0J0UTNDaHYxcmRPQmRkU3VjOW5aMndFY3M4MURIWFJPNTVOcElwVlE4dWlIIiwNCiAgICAgICAgICAgICJzZXJ2aWNlLWFjY291bnQtdXNlcm5hbWUiOiJkc2FhcyIsDQogICAgICAgICAgICAidG9rZW4tcHJvdmlkZXItaWQiOiI4ODZjN2VhMy1lZjk3LTQ0M2QtYjM0NS1kZTk0Yjk0YmI2NWQiLA0KICAgICAgICAgICAgImF1dGgtY2xpZW50LWlkIjoiYXV0aGVhc3QyYSIsDQogICAgICAgICAgICAiYXV0aC1jbGllbnQtc2VjcmV0IjoiYXV0aGVhc3QyYXNlY3JldCIsDQogICAgICAgICAgICAiYXV0aC1jbGllbnQtZGVmYXVsdC1zY29wZSI6InVzZXI6ZnVsbCINCiAgICAgICAgfQ0KICAgIF0NCn0=
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: f8cluster
  type: Opaque
  data:
    postgres.sslmode: require
    postgres.connection.maxidle: "90"
    postgres.connection.maxopen: "90"
    environment: prod-preview
    auth.url: https://auth.prod-preview.openshift.io
  